import { execSync } from 'node:child_process';

/**
 * Safely get current short git commit hash
 * @param {string} [cwd]
 * @returns {string|null}
 */
export function getGitCurrentCommit(cwd) {
  try {
    return execSync('git rev-parse --short HEAD', {
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
      timeout: 1000,
      cwd: cwd || undefined,
    }).trim();
  } catch (err) {
    return null;
  }
}

/**
 * Generate Markdown report for goal results
 * @param {Object} state
 * @returns {string}
 */
export function exportReportMarkdown(state) {
  if (!state) return '';
  const title = state.title || 'Goal Report';
  const status = state.state === 'COMPLETED' ? 'COMPLETED' : state.state;
  const elapsed = state.formattedElapsed || '0s';
  const iter = `${state.iterationsCount || 0}/${state.maxIterations || 25}`;
  const totalTokens = state.tokensUsage?.totalTokens || 0;
  const promptTokens = state.tokensUsage?.promptTokens || 0;
  const compTokens = state.tokensUsage?.completionTokens || 0;
  const gitCommit = state.gitStartCommit ? ` | **Git Start:** \`${state.gitStartCommit}\`` : '';

  let md = `# 🎯 Goal Report: ${title}\n\n`;
  md += `**Status:** \`${status}\` | **Duration:** \`${elapsed}\` | **Iterations:** \`${iter}\`${gitCommit}\n`;
  if (totalTokens > 0) {
    md += `**Tokens:** \`${totalTokens.toLocaleString('en-US')}\` (Prompt: \`${promptTokens.toLocaleString('en-US')}\`, Completion: \`${compTokens.toLocaleString('en-US')}\`)\n`;
  }
  md += '\n';

  if (state.description) {
    md += `### Description\n${state.description}\n\n`;
  }

  if (state.resultSummary) {
    md += `### Summary & Deliverables\n${state.resultSummary}\n\n`;
  }

  const milestones = state.milestones || [];
  if (milestones.length > 0) {
    md += `### Milestones\n| # | Status | Title | Notes |\n|---|---|---|---|\n`;
    milestones.forEach((m, idx) => {
      const mark = m.status === 'completed' ? '✅ Done' : m.status === 'in_progress' ? '🔄 In Progress' : '⏳ Pending';
      const cleanTitle = (m.title || '').replace(/\|/g, '\\|');
      const cleanNotes = (m.notes || '').replace(/\|/g, '\\|');
      md += `| ${idx + 1} | ${mark} | ${cleanTitle} | ${cleanNotes || '—'} |\n`;
    });
    md += '\n';
  }

  md += `*Generated by DSH Goal Engine at ${new Date().toISOString()}*\n`;
  return md;
}

/**
 * Generate GitHub / Gitea PR comment report with collapsible details
 * @param {Object} state
 * @returns {string}
 */
export function exportReportGitHubPR(state) {
  if (!state) return '';
  const title = state.title || 'Goal Report';
  const status = state.state === 'COMPLETED' ? 'COMPLETED' : state.state;
  const elapsed = state.formattedElapsed || '0s';
  const iter = `${state.iterationsCount || 0}/${state.maxIterations || 25}`;
  const totalTokens = state.tokensUsage?.totalTokens || 0;
  const promptTokens = state.tokensUsage?.promptTokens || 0;
  const compTokens = state.tokensUsage?.completionTokens || 0;
  const gitCommit = state.gitStartCommit ? ` &nbsp;|&nbsp; **Git Start:** \`${state.gitStartCommit}\` 📌` : '';

  let md = `## 🎯 Autonomous Goal Resolution: ${title}\n\n`;
  md += `> **Status:** \`${status}\` 🚀 &nbsp;|&nbsp; **Duration:** \`${elapsed}\` ⏱️ &nbsp;|&nbsp; **Iterations:** \`${iter}\` 🔄${gitCommit}\n\n`;

  if (totalTokens > 0) {
    md += `### 📊 Telemetry & Token Usage\n`;
    md += `- **Total Tokens:** \`${totalTokens.toLocaleString('en-US')}\` (Prompt: \`${promptTokens.toLocaleString('en-US')}\`, Completion: \`${compTokens.toLocaleString('en-US')}\`)\n\n`;
  }

  if (state.resultSummary) {
    md += `### 📦 Deliverables & Achievements\n${state.resultSummary}\n\n`;
  } else if (state.description) {
    md += `### 📝 Objective\n${state.description}\n\n`;
  }

  const milestones = state.milestones || [];
  if (milestones.length > 0) {
    const completedCount = milestones.filter((m) => m.status === 'completed').length;
    md += `<details>\n<summary><b>📋 Milestones Breakdown (${completedCount}/${milestones.length} Completed)</b></summary>\n\n`;
    md += `| # | Status | Milestone | Notes |\n|---|---|---|---|\n`;
    milestones.forEach((m, idx) => {
      const mark = m.status === 'completed' ? '✅ Done' : m.status === 'in_progress' ? '🔄 In Progress' : '⏳ Pending';
      const cleanTitle = (m.title || '').replace(/\|/g, '\\|');
      const cleanNotes = (m.notes || '').replace(/\|/g, '\\|');
      md += `| ${idx + 1} | ${mark} | ${cleanTitle} | ${cleanNotes || '—'} |\n`;
    });
    md += `\n</details>\n\n`;
  }

  md += `*Automated by [@goodandready/dsh-goal](https://github.com/GooDAnDReaDY/dsh-goal)*\n`;
  return md;
}

import fs from 'node:fs';
import path from 'node:path';

/**
 * Safely create a git milestone checkpoint
 * @param {object} milestone
 * @param {string} sessionId
 * @param {string} [cwd]
 * @returns {string|null} commit hash or tag name
 */
export function createMilestoneCheckpoint(milestone, sessionId = 'default', cwd) {
  if (!milestone || !milestone.id) return null;
  try {
    const status = execSync('git status --porcelain', {
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
      timeout: 2000,
      cwd: cwd || undefined,
    }).trim();

    // If there are changes, auto-commit checkpoint
    if (status) {
      execSync('git add -A', {
        stdio: ['ignore', 'ignore', 'ignore'],
        timeout: 3000,
        cwd: cwd || undefined,
      });
      const cleanTitle = (milestone.title || '').replace(/[\"\`\$]/g, '');
      const msg = `checkpoint(goal): [${milestone.id}] ${cleanTitle}`;
      execSync(`git commit -m "${msg}" --no-verify`, {
        stdio: ['ignore', 'ignore', 'ignore'],
        timeout: 5000,
        cwd: cwd || undefined,
      });
    }

    const hash = execSync('git rev-parse --short HEAD', {
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
      timeout: 1000,
      cwd: cwd || undefined,
    }).trim();

    return hash || null;
  } catch (err) {
    return null;
  }
}

/**
 * Rollback working tree to a specific commit checkpoint
 * @param {string} commitHash
 * @param {string} [cwd]
 * @returns {boolean}
 */
export function rollbackToCheckpoint(commitHash, cwd) {
  if (!commitHash || typeof commitHash !== 'string') return false;
  try {
    const cleanHash = commitHash.trim().replace(/[^a-zA-Z0-9_-]/g, '');
    if (!cleanHash) return false;
    execSync(`git checkout ${cleanHash} -- .`, {
      stdio: ['ignore', 'ignore', 'ignore'],
      timeout: 5000,
      cwd: cwd || undefined,
    });
    return true;
  } catch (err) {
    return false;
  }
}

/**
 * Save full goal execution artifact markdown file into .dsh/goals/
 * @param {object} state
 * @param {string} [cwd]
 * @returns {{ relativePath: string, fullPath: string, content: string }|null}
 */
export function saveGoalArtifact(state, cwd) {
  if (!state || !state.title) return null;
  try {
    const root = cwd || process.cwd();
    const targetDir = path.join(root, '.dsh', 'goals');
    if (!fs.existsSync(targetDir)) {
      fs.mkdirSync(targetDir, { recursive: true });
    }

    const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
    const safeTitle = (state.title || 'goal')
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '')
      .slice(0, 40) || 'run';

    const filename = `${timestamp}-${safeTitle}.md`;
    const fullPath = path.join(targetDir, filename);
    const relativePath = path.join('.dsh', 'goals', filename).replace(/\\/g, '/');

    const content = exportReportMarkdown(state);
    fs.writeFileSync(fullPath, content, 'utf8');

    return { relativePath, fullPath, content };
  } catch (err) {
    return null;
  }
}
