import { execSync } from 'node:child_process';

/**
 * Safely get current short git commit hash
 * @param {string} [cwd]
 * @returns {string|null}
 */
export function getGitCurrentCommit(cwd) {
  try {
    return execSync('git rev-parse --short HEAD', {
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
      timeout: 1000,
      cwd: cwd || undefined,
    }).trim();
  } catch (err) {
    return null;
  }
}

/**
 * Generate Markdown report for goal results
 * @param {Object} state
 * @returns {string}
 */
export function exportReportMarkdown(state) {
  if (!state) return '';
  const title = state.title || 'Goal Report';
  const status = state.state === 'COMPLETED' ? 'COMPLETED' : state.state;
  const elapsed = state.formattedElapsed || '0s';
  const iter = `${state.iterationsCount || 0}/${state.maxIterations || 25}`;
  const totalTokens = state.tokensUsage?.totalTokens || 0;
  const promptTokens = state.tokensUsage?.promptTokens || 0;
  const compTokens = state.tokensUsage?.completionTokens || 0;
  const gitCommit = state.gitStartCommit ? ` | **Git Start:** \`${state.gitStartCommit}\`` : '';

  let md = `# 🎯 Goal Report: ${title}\n\n`;
  md += `**Status:** \`${status}\` | **Duration:** \`${elapsed}\` | **Iterations:** \`${iter}\`${gitCommit}\n`;
  if (totalTokens > 0) {
    md += `**Tokens:** \`${totalTokens.toLocaleString('en-US')}\` (Prompt: \`${promptTokens.toLocaleString('en-US')}\`, Completion: \`${compTokens.toLocaleString('en-US')}\`)\n`;
  }
  md += '\n';

  if (state.description) {
    md += `### Description\n${state.description}\n\n`;
  }

  if (state.resultSummary) {
    md += `### Summary & Deliverables\n${state.resultSummary}\n\n`;
  }

  const milestones = state.milestones || [];
  if (milestones.length > 0) {
    md += `### Milestones\n| # | Status | Title | Notes |\n|---|---|---|---|\n`;
    milestones.forEach((m, idx) => {
      const mark = m.status === 'completed' ? '✅ Done' : m.status === 'in_progress' ? '🔄 In Progress' : '⏳ Pending';
      const cleanTitle = (m.title || '').replace(/\|/g, '\\|');
      const cleanNotes = (m.notes || '').replace(/\|/g, '\\|');
      md += `| ${idx + 1} | ${mark} | ${cleanTitle} | ${cleanNotes || '—'} |\n`;
    });
    md += '\n';
  }

  md += `*Generated by DSH Goal Engine at ${new Date().toISOString()}*\n`;
  return md;
}

/**
 * Generate GitHub / Gitea PR comment report with collapsible details
 * @param {Object} state
 * @returns {string}
 */
export function exportReportGitHubPR(state) {
  if (!state) return '';
  const title = state.title || 'Goal Report';
  const status = state.state === 'COMPLETED' ? 'COMPLETED' : state.state;
  const elapsed = state.formattedElapsed || '0s';
  const iter = `${state.iterationsCount || 0}/${state.maxIterations || 25}`;
  const totalTokens = state.tokensUsage?.totalTokens || 0;
  const promptTokens = state.tokensUsage?.promptTokens || 0;
  const compTokens = state.tokensUsage?.completionTokens || 0;
  const gitCommit = state.gitStartCommit ? ` &nbsp;|&nbsp; **Git Start:** \`${state.gitStartCommit}\` 📌` : '';

  let md = `## 🎯 Autonomous Goal Resolution: ${title}\n\n`;
  md += `> **Status:** \`${status}\` 🚀 &nbsp;|&nbsp; **Duration:** \`${elapsed}\` ⏱️ &nbsp;|&nbsp; **Iterations:** \`${iter}\` 🔄${gitCommit}\n\n`;

  if (totalTokens > 0) {
    md += `### 📊 Telemetry & Token Usage\n`;
    md += `- **Total Tokens:** \`${totalTokens.toLocaleString('en-US')}\` (Prompt: \`${promptTokens.toLocaleString('en-US')}\`, Completion: \`${compTokens.toLocaleString('en-US')}\`)\n\n`;
  }

  if (state.resultSummary) {
    md += `### 📦 Deliverables & Achievements\n${state.resultSummary}\n\n`;
  } else if (state.description) {
    md += `### 📝 Objective\n${state.description}\n\n`;
  }

  const milestones = state.milestones || [];
  if (milestones.length > 0) {
    const completedCount = milestones.filter((m) => m.status === 'completed').length;
    md += `<details>\n<summary><b>📋 Milestones Breakdown (${completedCount}/${milestones.length} Completed)</b></summary>\n\n`;
    md += `| # | Status | Milestone | Notes |\n|---|---|---|---|\n`;
    milestones.forEach((m, idx) => {
      const mark = m.status === 'completed' ? '✅ Done' : m.status === 'in_progress' ? '🔄 In Progress' : '⏳ Pending';
      const cleanTitle = (m.title || '').replace(/\|/g, '\\|');
      const cleanNotes = (m.notes || '').replace(/\|/g, '\\|');
      md += `| ${idx + 1} | ${mark} | ${cleanTitle} | ${cleanNotes || '—'} |\n`;
    });
    md += `\n</details>\n\n`;
  }

  md += `*Automated by [@goodandready/dsh-goal](https://github.com/GooDAnDReaDY/dsh-goal)*\n`;
  return md;
}
