import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { execSync } from 'node:child_process';

/**
 * Изолированное ядро управления состоянием цели (Goal Engine).
 * Не имеет внешних зависимостей, 100% тестируемо через node --test.
 */

export const GoalState = {
  IDLE: 'IDLE',
  PLANNING: 'PLANNING',
  RUNNING: 'RUNNING',
  PAUSED: 'PAUSED',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
};

export const MilestoneStatus = {
  PENDING: 'pending',
  IN_PROGRESS: 'in_progress',
  COMPLETED: 'completed',
  FAILED: 'failed',
};

/**
 * Форматирование времени в лаконичную строку (например: "2s", "45s", "1m 15s", "2h 5m")
 * @param {number} totalSeconds
 * @returns {string}
 */
export function formatElapsed(totalSeconds) {
  const sec = Math.max(0, Math.floor(totalSeconds));
  if (sec < 60) return `${sec}s`;
  const mins = Math.floor(sec / 60);
  const remainingSec = sec % 60;
  if (mins < 60) {
    return remainingSec > 0 ? `${mins}m ${remainingSec}s` : `${mins}m`;
  }
  const hours = Math.floor(mins / 60);
  const remainingMins = mins % 60;
  return remainingMins > 0 ? `${hours}h ${remainingMins}m` : `${hours}h`;
}

/**
 * Форматирование расчетного оставшегося времени (ETA)
 * @param {number|null} seconds
 * @returns {string|null}
 */
export function formatETA(seconds) {
  if (seconds == null || isNaN(seconds)) return null;
  const sec = Math.max(0, Math.floor(seconds));
  if (sec < 60) return `~${sec}s`;
  const mins = Math.round(sec / 60);
  if (mins < 60) return `~${mins}m`;
  const hours = Math.floor(mins / 60);
  const remainingMins = mins % 60;
  return remainingMins > 0 ? `~${hours}h ${remainingMins}m` : `~${hours}h`;
}

/**
 * Автоматическое определение языка текста (кириллица -> ru, иероглифы -> zh, иначе en)
 * @param {string} text
 * @param {string} [fallback='en']
 * @returns {'ru' | 'en' | 'zh'}
 */
export function detectLanguage(text, fallback = 'en') {
  if (!text || typeof text !== 'string') return fallback;
  if (/[а-яёА-ЯЁ]/i.test(text)) {
    return 'ru';
  }
  if (/[\u4e00-\u9fa5]/.test(text)) {
    return 'zh';
  }
  return 'en';
}


/**
 * Безопасное получение текущего короткого Git commit hash
 * @returns {string|null}
 */
export function getGitCurrentCommit() {
  try {
    return execSync('git rev-parse --short HEAD', {
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
      timeout: 1000,
    }).trim();
  } catch (_) {
    return null;
  }
}

/**
 * Генератор Markdown-отчета о результатах цели
 * @param {Object} state
 * @returns {string}
 */
export function exportReportMarkdown(state) {
  if (!state) return '';
  const title = state.title || 'Goal Report';
  const status = state.state === 'COMPLETED' ? 'COMPLETED' : state.state;
  const elapsed = state.formattedElapsed || '0s';
  const iter = `${state.iterationsCount || 0}/${state.maxIterations || 25}`;
  const totalTokens = state.tokensUsage?.totalTokens || 0;
  const promptTokens = state.tokensUsage?.promptTokens || 0;
  const compTokens = state.tokensUsage?.completionTokens || 0;
  const gitCommit = state.gitStartCommit ? ` | **Git Start:** \`${state.gitStartCommit}\`` : '';

  let md = `# 🎯 Goal Report: ${title}\n\n`;
  md += `**Status:** \`${status}\` | **Duration:** \`${elapsed}\` | **Iterations:** \`${iter}\`${gitCommit}\n`;
  if (totalTokens > 0) {
    md += `**Tokens:** \`${totalTokens.toLocaleString('en-US')}\` (Prompt: \`${promptTokens.toLocaleString('en-US')}\`, Completion: \`${compTokens.toLocaleString('en-US')}\`)\n`;
  }
  md += '\n';

  if (state.description) {
    md += `### Description\n${state.description}\n\n`;
  }

  if (state.resultSummary) {
    md += `### Summary & Deliverables\n${state.resultSummary}\n\n`;
  }

  const milestones = state.milestones || [];
  if (milestones.length > 0) {
    md += `### Milestones\n| # | Status | Title | Notes |\n|---|---|---|---|\n`;
    milestones.forEach((m, idx) => {
      const mark = m.status === 'completed' ? '✅ Done' : m.status === 'in_progress' ? '🔄 In Progress' : '⏳ Pending';
      const cleanTitle = (m.title || '').replace(/\|/g, '\\|');
      const cleanNotes = (m.notes || '').replace(/\|/g, '\\|');
      md += `| ${idx + 1} | ${mark} | ${cleanTitle} | ${cleanNotes || '—'} |\n`;
    });
    md += '\n';
  }

  md += `*Generated by DSH Goal Engine at ${new Date().toISOString()}*\n`;
  return md;
}

/**
 * Генератор отчета в формате GitHub / Gitea PR Comment со спойлерами
 * @param {Object} state
 * @returns {string}
 */
export function exportReportGitHubPR(state) {
  if (!state) return '';
  const title = state.title || 'Goal Report';
  const status = state.state === 'COMPLETED' ? 'COMPLETED' : state.state;
  const elapsed = state.formattedElapsed || '0s';
  const iter = `${state.iterationsCount || 0}/${state.maxIterations || 25}`;
  const totalTokens = state.tokensUsage?.totalTokens || 0;
  const promptTokens = state.tokensUsage?.promptTokens || 0;
  const compTokens = state.tokensUsage?.completionTokens || 0;
  const gitCommit = state.gitStartCommit ? ` &nbsp;|&nbsp; **Git Start:** \`${state.gitStartCommit}\` 📌` : '';

  let md = `## 🎯 Autonomous Goal Resolution: ${title}\n\n`;
  md += `> **Status:** \`${status}\` 🚀 &nbsp;|&nbsp; **Duration:** \`${elapsed}\` ⏱️ &nbsp;|&nbsp; **Iterations:** \`${iter}\` 🔄${gitCommit}\n\n`;

  if (totalTokens > 0) {
    md += `### 📊 Telemetry & Token Usage\n`;
    md += `- **Total Tokens:** \`${totalTokens.toLocaleString('en-US')}\` (Prompt: \`${promptTokens.toLocaleString('en-US')}\`, Completion: \`${compTokens.toLocaleString('en-US')}\`)\n\n`;
  }

  if (state.resultSummary) {
    md += `### 📦 Deliverables & Achievements\n${state.resultSummary}\n\n`;
  } else if (state.description) {
    md += `### 📝 Objective\n${state.description}\n\n`;
  }

  const milestones = state.milestones || [];
  if (milestones.length > 0) {
    const completedCount = milestones.filter(m => m.status === 'completed').length;
    md += `<details>\n<summary><b>📋 Milestones Breakdown (${completedCount}/${milestones.length} Completed)</b></summary>\n\n`;
    md += `| # | Status | Milestone | Notes |\n|---|---|---|---|\n`;
    milestones.forEach((m, idx) => {
      const mark = m.status === 'completed' ? '✅ Done' : m.status === 'in_progress' ? '🔄 In Progress' : '⏳ Pending';
      const cleanTitle = (m.title || '').replace(/\|/g, '\\|');
      const cleanNotes = (m.notes || '').replace(/\|/g, '\\|');
      md += `| ${idx + 1} | ${mark} | ${cleanTitle} | ${cleanNotes || '—'} |\n`;
    });
    md += `\n</details>\n\n`;
  }

  md += `*Automated by [@goodandready/dsh-goal](https://github.com/GooDAnDReaDY/dsh-goal)*\n`;
  return md;
}

export class GoalEngine {
  constructor(options = {}) {
    this.defaultMaxIterations = options.defaultMaxIterations ?? 25;
    this.autoDrive = options.autoDrive ?? true;
    this.enableSound = options.enableSound ?? true;
    this.showQuickLaunchButton = options.showQuickLaunchButton ?? true;
    this.consecutiveToolFailureLimit = options.consecutiveToolFailureLimit ?? 3;
    this.maxSessions = options.maxSessions ?? 100;
    this.goals = new Map();
    this.listeners = new Set();
    this.saveTimer = null;
    this.stallCounters = new Map(); // sessionId -> number of consecutive turns without progress
    this.toolFailureCounters = new Map(); // sessionId -> number of consecutive turns with tool errors

    const defaultStorageDir = process.env.DSH_HOME || path.join(os.homedir(), '.dsh');
    this.storagePath = options.storagePath ?? null;

    this.loadStateFromDisk();
  }

  get currentGoal() {
    return this.goals.get('default') || null;
  }

  set currentGoal(val) {
    if (val) {
      this.goals.set('default', val);
    } else {
      this.goals.delete('default');
    }
  }

  loadStateFromDisk() {
    if (!this.storagePath) return;
    try {
      if (fs.existsSync(this.storagePath)) {
        const raw = fs.readFileSync(this.storagePath, 'utf8');
        const data = JSON.parse(raw);
        if (data && typeof data === 'object') {
          let dirty = false;
          if (data.sessions && typeof data.sessions === 'object') {
            for (const [sid, goal] of Object.entries(data.sessions)) {
              if (goal && goal.id && goal.title) {
                // Item 4: Crash Hydration — если цель осталась в RUNNING после перезапуска/падения DSH,
                // переводим в PAUSED с понятной причиной и фиксацией времени
                if (goal.state === GoalState.RUNNING) {
                  goal.state = GoalState.PAUSED;
                  goal.pausedAt = Date.now();
                  if (!Array.isArray(goal.logs)) goal.logs = [];
                  goal.logs.push({
                    timestamp: Date.now(),
                    type: 'warning',
                    message: 'Harness was restarted — click ▶️ to resume',
                  });
                  if (goal.logs.length > 100) goal.logs = goal.logs.slice(-100);
                  dirty = true;
                }
                if (!goal.tokensUsage) {
                  goal.tokensUsage = { promptTokens: 0, completionTokens: 0, totalTokens: 0 };
                }
                if (!goal.lang) {
                  goal.lang = detectLanguage(goal.title);
                }
                this.goals.set(sid, goal);
              }
            }
          } else if (data.id && data.title) {
            if (data.state === GoalState.RUNNING) {
              data.state = GoalState.PAUSED;
              data.pausedAt = Date.now();
              if (!Array.isArray(data.logs)) data.logs = [];
              data.logs.push({
                timestamp: Date.now(),
                type: 'warning',
                message: 'Harness was restarted — click ▶️ to resume',
              });
              if (data.logs.length > 100) data.logs = data.logs.slice(-100);
              dirty = true;
            }
            if (!data.tokensUsage) {
              data.tokensUsage = { promptTokens: 0, completionTokens: 0, totalTokens: 0 };
            }
            if (!data.lang) {
              data.lang = detectLanguage(data.title);
            }
            this.goals.set('default', data);
          }
          if (dirty) {
            this.scheduleSave(true);
          }
        }
      }
    } catch (err) {
      console.warn('[GoalEngine] Failed to load state from disk:', err);
    }
  }

  scheduleSave(immediate = false) {
    if (!this.storagePath) return;
    if (immediate) {
      if (this.saveTimer) {
        clearTimeout(this.saveTimer);
        this.saveTimer = null;
      }
      this.writeStateToDiskSync();
      return;
    }
    if (!this.saveTimer) {
      this.saveTimer = setTimeout(() => {
        this.saveTimer = null;
        this.writeStateToDiskSync();
      }, 250);
      if (typeof this.saveTimer.unref === 'function') {
        this.saveTimer.unref();
      }
    }
  }

  writeStateToDiskSync() {
    if (!this.storagePath) return;
    try {
      if (this.goals.size === 0) {
        if (fs.existsSync(this.storagePath)) {
          fs.unlinkSync(this.storagePath);
        }
        return;
      }
      const sessionsObj = {};
      for (const [sid, goal] of this.goals.entries()) {
        sessionsObj[sid] = goal;
      }
      const payload = {
        version: 2,
        sessions: sessionsObj,
        ...(this.goals.has('default') ? this.goals.get('default') : {}),
      };
      const dir = path.dirname(this.storagePath);
      if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
      }
      const tmp = `${this.storagePath}.tmp.${Date.now()}`;
      fs.writeFileSync(tmp, JSON.stringify(payload, null, 2), 'utf8');
      fs.renameSync(tmp, this.storagePath);
    } catch (err) {
      console.warn('[GoalEngine] Failed to write state to disk:', err);
    }
  }

  flushSync() {
    if (this.saveTimer) {
      clearTimeout(this.saveTimer);
      this.saveTimer = null;
    }
    this.writeStateToDiskSync();
  }

  saveStateToDisk() {
    this.flushSync();
  }

  /**
   * Подписка на изменение состояния
   * @param {Function} callback
   * @returns {Function} unsubscribe
   */
  subscribe(callback) {
    this.listeners.add(callback);
    return () => this.listeners.delete(callback);
  }

  emit(sessionId = 'default', immediate = false) {
    this.scheduleSave(immediate);
    const sid = sessionId || 'default';
    const snapshot = this.getSnapshot(sid);
    for (const listener of this.listeners) {
      try {
        listener(snapshot, sid);
      } catch (err) {
        console.error('[GoalEngine] Listener error:', err);
      }
    }
  }

  /**
   * Отслеживание прогресса для Smart Progress Guard
   */
  recordProgress(sessionId = 'default') {
    const sid = sessionId || 'default';
    this.stallCounters.set(sid, 0);
  }

  incrementStallCount(sessionId = 'default') {
    const sid = sessionId || 'default';
    const current = this.stallCounters.get(sid) || 0;
    const next = current + 1;
    this.stallCounters.set(sid, next);
    return next;
  }

  getStallCount(sessionId = 'default') {
    const sid = sessionId || 'default';
    return this.stallCounters.get(sid) || 0;
  }

  /**
   * Динамическое обновление настроек на лету
   * @param {Object} config
   */
  updateConfig(config = {}) {
    if (typeof config.defaultMaxIterations === 'number' && config.defaultMaxIterations >= 1) {
      const prev = this.defaultMaxIterations;
      this.defaultMaxIterations = config.defaultMaxIterations;
      for (const [_, goal] of this.goals) {
        if (goal && goal.maxIterations === prev) {
          goal.maxIterations = config.defaultMaxIterations;
        }
      }
    }
    if (typeof config.autoDrive === 'boolean') {
      this.autoDrive = config.autoDrive;
    }
    if (typeof config.enableSound === 'boolean') {
      this.enableSound = config.enableSound;
    }
    if (typeof config.showQuickLaunchButton === 'boolean') {
      this.showQuickLaunchButton = config.showQuickLaunchButton;
    }
    if (typeof config.consecutiveToolFailureLimit === 'number') {
      this.consecutiveToolFailureLimit = Math.max(0, config.consecutiveToolFailureLimit);
    }
    this.emit();
  }

  /**
   * Получение цели сессии
   */
  getGoal(sessionId = 'default') {
    return this.goals.get(sessionId || 'default') || null;
  }

  /**
   * Очистка старых неактивных сессий во избежание утечек памяти
   */

  /**
   * Управление счетчиком повторяющихся ошибок инструментов
   */
  incrementToolFailureCount(sessionId = 'default') {
    const sid = sessionId || 'default';
    const current = this.toolFailureCounters.get(sid) || 0;
    const next = current + 1;
    this.toolFailureCounters.set(sid, next);
    return next;
  }

  resetToolFailureCount(sessionId = 'default') {
    const sid = sessionId || 'default';
    this.toolFailureCounters.set(sid, 0);
  }

  getToolFailureCount(sessionId = 'default') {
    const sid = sessionId || 'default';
    return this.toolFailureCounters.get(sid) || 0;
  }

  /**
   * Живая корректировка цели / добавление уточнений (Live Steering / Nudge)
   * @param {string} text
   * @param {string} [sessionId='default']
   */
  nudge(text, sessionId = 'default') {
    const sid = sessionId || 'default';
    const goal = this.goals.get(sid);
    if (!goal) return this.getSnapshot(sid);

    const clean = String(text || '').trim();
    if (!clean) return this.getSnapshot(sid);

    if (!Array.isArray(goal.nudges)) {
      goal.nudges = [];
    }
    const now = Date.now();
    goal.nudges.push({ text: clean, timestamp: now });
    goal.pendingNudge = clean;
    goal.logs.push({
      timestamp: now,
      type: 'info',
      message: `User steering / clarification: "${clean}"`,
    });
    if (goal.logs.length > 100) {
      goal.logs = goal.logs.slice(-100);
    }

    this.emit(sid, true);
    return this.getSnapshot(sid);
  }

  consumePendingNudge(sessionId = 'default') {
    const sid = sessionId || 'default';
    const goal = this.goals.get(sid);
    if (!goal || !goal.pendingNudge) return null;
    const nudge = goal.pendingNudge;
    goal.pendingNudge = null;
    this.emit(sid);
    return nudge;
  }

  pruneInactiveSessions() {
    if (this.goals.size < this.maxSessions) return;
    const inactive = [];
    for (const [sid, goal] of this.goals.entries()) {
      if (sid === 'default') continue;
      if (goal.state === GoalState.COMPLETED || goal.state === GoalState.CANCELLED || goal.state === GoalState.FAILED) {
        inactive.push({ sid, completedAt: goal.completedAt || goal.startedAt || 0 });
      }
    }
    inactive.sort((a, b) => a.completedAt - b.completedAt);
    while (this.goals.size >= this.maxSessions && inactive.length > 0) {
      const oldest = inactive.shift();
      this.goals.delete(oldest.sid);
      this.stallCounters.delete(oldest.sid);
    }
  }

  /**
   * Запуск новой цели
   * @param {string} title
   * @param {Object} options
   * @param {string} [sessionId='default']
   */
  startGoal(title, options = {}, sessionId = 'default') {
    if (!title || typeof title !== 'string' || !title.trim()) {
      throw new Error('Goal title cannot be empty');
    }

    this.pruneInactiveSessions();

    const cleanTitle = title.trim();
    const now = Date.now();
    const sid = sessionId || 'default';
    this.stallCounters.set(sid, 0);

    const gitCommit = options.gitStartCommit !== undefined
      ? options.gitStartCommit
      : getGitCurrentCommit();

    this.toolFailureCounters.set(sid, 0);

    const goal = {
      id: `goal-${now}-${Math.random().toString(36).substring(2, 7)}`,
      sessionId: sid,
      title: cleanTitle,
      description: options.description?.trim() || '',
      lang: options.lang || detectLanguage(cleanTitle),
      state: GoalState.RUNNING,
      startedAt: now,
      pausedAt: null,
      totalPausedDurationMs: 0,
      completedAt: null,
      iterationsCount: 0,
      maxIterations: options.maxIterations ?? this.defaultMaxIterations,
      gitStartCommit: gitCommit || null,
      pendingNudge: null,
      nudges: [],
      milestones: [],
      tokensUsage: { promptTokens: 0, completionTokens: 0, totalTokens: 0 },
      logs: [
        {
          timestamp: now,
          type: 'info',
          message: `Goal initiated: "${cleanTitle}"` + (gitCommit ? ` (Git: ${gitCommit})` : ''),
        },
      ],
      resultSummary: '',
    };

    this.goals.set(sid, goal);

    if (Array.isArray(options.milestones) && options.milestones.length > 0) {
      this.addMilestones(options.milestones, false, sid);
    }

    this.emit(sid, true);
    return this.getSnapshot(sid);
  }

  /**
   * Приостановка автономного цикла цели
   */
  pause(reason = 'User requested pause', sessionId = 'default') {
    const sid = sessionId || 'default';
    const goal = this.goals.get(sid);
    if (!goal || goal.state !== GoalState.RUNNING) {
      return this.getSnapshot(sid);
    }

    goal.state = GoalState.PAUSED;
    goal.pausedAt = Date.now();
    goal.logs.push({
      timestamp: Date.now(),
      type: 'warning',
      message: `Paused: ${reason}`,
    });

    if (goal.logs.length > 100) {
      goal.logs = goal.logs.slice(-100);
    }

    this.emit(sid, true);
    return this.getSnapshot(sid);
  }

  /**
   * Возобновление выполнения цели
   */
  resume(sessionId = 'default') {
    const sid = sessionId || 'default';
    const goal = this.goals.get(sid);
    if (!goal || goal.state !== GoalState.PAUSED) {
      return this.getSnapshot(sid);
    }

    const now = Date.now();
    if (goal.pausedAt) {
      goal.totalPausedDurationMs += now - goal.pausedAt;
      goal.pausedAt = null;
    }

    goal.state = GoalState.RUNNING;
    this.stallCounters.set(sid, 0); // сбрасываем счетчик простоя при возобновлении

    goal.logs.push({
      timestamp: now,
      type: 'info',
      message: 'Goal resumed',
    });

    if (goal.logs.length > 100) {
      goal.logs = goal.logs.slice(-100);
    }

    this.emit(sid, true);
    return this.getSnapshot(sid);
  }

  /**
   * Отмена цели
   */
  cancel(reason = 'Cancelled by user', sessionId = 'default') {
    const sid = sessionId || 'default';
    const goal = this.goals.get(sid);
    if (!goal) return null;

    goal.state = GoalState.CANCELLED;
    goal.completedAt = Date.now();
    goal.logs.push({
      timestamp: Date.now(),
      type: 'warning',
      message: `Cancelled: ${reason}`,
    });

    if (goal.logs.length > 100) {
      goal.logs = goal.logs.slice(-100);
    }

    this.emit(sid, true);
    return this.getSnapshot(sid);
  }

  /**
   * Очистка / сброс цели в IDLE
   */
  clear(sessionId = 'default') {
    const sid = sessionId || 'default';
    this.goals.delete(sid);
    this.stallCounters.delete(sid);
    this.emit(sid, true);
    return this.getSnapshot(sid);
  }

  /**
   * Успешное завершение цели
   */
  completeGoal(summary = '', sessionId = 'default') {
    const sid = sessionId || 'default';
    const goal = this.goals.get(sid);
    if (!goal) return null;

    const now = Date.now();
    goal.state = GoalState.COMPLETED;
    goal.completedAt = now;
    goal.resultSummary = summary;
    goal.logs.push({
      timestamp: now,
      type: 'info',
      message: `Goal completed successfully: ${summary || 'All objectives met.'}`,
    });

    if (goal.logs.length > 100) {
      goal.logs = goal.logs.slice(-100);
    }

    // Завершаем все активные milestones
    for (const m of goal.milestones) {
      if (m.status === MilestoneStatus.IN_PROGRESS || m.status === MilestoneStatus.PENDING) {
        m.status = MilestoneStatus.COMPLETED;
      }
    }

    this.stallCounters.delete(sid);
    this.emit(sid, true);
    return this.getSnapshot(sid);
  }

  /**
   * Добавление вех (milestones)
   */
  addMilestones(milestonesList, shouldEmit = true, sessionId = 'default') {
    const sid = sessionId || 'default';
    const goal = this.goals.get(sid);
    if (!goal || !Array.isArray(milestonesList)) return;

    for (const item of milestonesList) {
      const itemTitle = typeof item === 'string' ? item : item.title;
      if (!itemTitle || !itemTitle.trim()) continue;

      const mId = (typeof item === 'object' && item.id) ? item.id : `m-${goal.milestones.length + 1}`;
      goal.milestones.push({
        id: String(mId),
        title: itemTitle.trim(),
        status: (typeof item === 'object' && item.status) ? item.status : MilestoneStatus.PENDING,
        notes: (typeof item === 'object' && item.notes) ? item.notes : '',
      });
    }

    this.recordProgress(sid);
    if (shouldEmit) this.emit(sid);
  }

  /**
   * Обновление конкретной вехи
   */
  updateMilestone(id, status, notes = '', sessionId = 'default') {
    const sid = sessionId || 'default';
    const goal = this.goals.get(sid);
    if (!goal) return false;

    const target = goal.milestones.find((m) => m.id === String(id));
    if (!target) return false;

    if (status && Object.values(MilestoneStatus).includes(status)) {
      target.status = status;
    }
    if (notes) {
      target.notes = String(notes);
    }

    goal.logs.push({
      timestamp: Date.now(),
      type: 'milestone',
      message: `Milestone [${target.title}] status -> ${target.status}`,
    });

    if (goal.logs.length > 100) {
      goal.logs = goal.logs.slice(-100);
    }

    this.recordProgress(sid);
    this.emit(sid);
    return true;
  }

  /**
   * Увеличение счётчика итераций turn
   */
  incrementIteration(sessionId = 'default') {
    const sid = sessionId || 'default';
    const goal = this.goals.get(sid);
    if (!goal || goal.state !== GoalState.RUNNING) {
      return false;
    }

    goal.iterationsCount += 1;

    if (goal.iterationsCount >= goal.maxIterations) {
      goal.state = GoalState.FAILED;
      goal.logs.push({
        timestamp: Date.now(),
        type: 'error',
        message: `Safety limit reached: maximum ${goal.maxIterations} iterations exceeded.`,
      });
      if (goal.logs.length > 100) {
        goal.logs = goal.logs.slice(-100);
      }
      this.emit(sid, true);
      return false;
    }

    this.emit(sid);
    return true;
  }

  /**
   * Подсчёт времени в секундах
   */
  getElapsedSeconds(sessionId = 'default') {
    const sid = sessionId || 'default';
    const goal = this.goals.get(sid);
    if (!goal) return 0;
    const { startedAt, pausedAt, totalPausedDurationMs, completedAt } = goal;
    const endTime = completedAt || (pausedAt || Date.now());
    const elapsedMs = Math.max(0, endTime - startedAt - totalPausedDurationMs);
    return Math.floor(elapsedMs / 1000);
  }

  /**
   * Накопление статистики использования токенов сессии
   * @param {Object} usage
   * @param {string} [sessionId='default']
   */
  addTokenUsage(usage, sessionId = 'default') {
    if (!usage || typeof usage !== 'object') return;
    const sid = sessionId || 'default';
    const goal = this.goals.get(sid);
    if (!goal) return;

    if (!goal.tokensUsage) {
      goal.tokensUsage = { promptTokens: 0, completionTokens: 0, totalTokens: 0 };
    }

    const prompt = Number(usage.promptTokens ?? usage.input_tokens ?? usage.prompt_tokens ?? 0) || 0;
    const completion = Number(usage.completionTokens ?? usage.output_tokens ?? usage.completion_tokens ?? 0) || 0;
    const total = Number(usage.totalTokens ?? usage.total_tokens ?? (prompt + completion)) || (prompt + completion);

    goal.tokensUsage.promptTokens += prompt;
    goal.tokensUsage.completionTokens += completion;
    goal.tokensUsage.totalTokens += total;

    this.emit(sid);
  }

  /**
   * Интеллектуальный расчет прогноза оставшегося времени (ETA)
   * на основе средней скорости выполнения завершенных вех
   * @param {string} [sessionId='default']
   * @returns {number|null}
   */
  getEstimatedRemainingSeconds(sessionId = 'default') {
    const sid = sessionId || 'default';
    const goal = this.goals.get(sid);
    if (!goal || goal.state !== GoalState.RUNNING) return null;

    const total = goal.milestones.length;
    if (total === 0) return null;

    const completedCount = goal.milestones.filter((m) => m.status === MilestoneStatus.COMPLETED).length;
    if (completedCount === 0 || completedCount >= total) return null;

    const elapsed = this.getElapsedSeconds(sid);
    if (elapsed <= 0) return null;

    const avgSecPerMilestone = elapsed / completedCount;
    const remainingCount = total - completedCount;
    return Math.max(1, Math.round(avgSecPerMilestone * remainingCount));
  }

  /**
   * Снимок состояния для передачи клиенту / API
   */
  getSnapshot(sessionId = 'default') {
    const sid = sessionId || 'default';
    const goal = this.goals.get(sid);
    if (!goal) {
      return {
        sessionId: sid,
        hasActiveGoal: false,
        state: GoalState.IDLE,
        title: '',
        startedAt: null,
        pausedAt: null,
        totalPausedDurationMs: 0,
        completedAt: null,
        elapsedSeconds: 0,
        formattedElapsed: '0s',
        estimatedRemainingSeconds: null,
        formattedETA: null,
        lang: 'en',
        tokensUsage: { promptTokens: 0, completionTokens: 0, totalTokens: 0 },
        milestones: [],
        progressPercent: 0,
        iterationsCount: 0,
        maxIterations: this.defaultMaxIterations,
        autoDrive: this.autoDrive,
        enableSound: this.enableSound,
        showQuickLaunchButton: this.showQuickLaunchButton,
        gitStartCommit: null,
        pendingNudge: null,
        toolFailureCount: 0,
        consecutiveToolFailureLimit: this.consecutiveToolFailureLimit,
      };
    }

    const elapsed = this.getElapsedSeconds(sid);
    const milestones = goal.milestones;
    const completedCount = milestones.filter((m) => m.status === MilestoneStatus.COMPLETED).length;
    const progressPercent = milestones.length > 0 ? Math.round((completedCount / milestones.length) * 100) : 0;
    const estSec = this.getEstimatedRemainingSeconds(sid);

    return {
      sessionId: sid,
      hasActiveGoal: true,
      id: goal.id,
      state: goal.state,
      title: goal.title,
      description: goal.description,
      lang: goal.lang || detectLanguage(goal.title),
      startedAt: goal.startedAt,
      pausedAt: goal.pausedAt,
      totalPausedDurationMs: goal.totalPausedDurationMs,
      completedAt: goal.completedAt,
      elapsedSeconds: elapsed,
      formattedElapsed: formatElapsed(elapsed),
      estimatedRemainingSeconds: estSec,
      formattedETA: formatETA(estSec),
      tokensUsage: goal.tokensUsage || { promptTokens: 0, completionTokens: 0, totalTokens: 0 },
      iterationsCount: goal.iterationsCount,
      maxIterations: goal.maxIterations,
      milestones,
      progressPercent,
      logs: goal.logs,
      resultSummary: goal.resultSummary,
      autoDrive: this.autoDrive,
      enableSound: this.enableSound,
      showQuickLaunchButton: this.showQuickLaunchButton,
      gitStartCommit: goal.gitStartCommit || null,
      pendingNudge: goal.pendingNudge || null,
      toolFailureCount: this.getToolFailureCount(sid),
      consecutiveToolFailureLimit: this.consecutiveToolFailureLimit,
    };
  }

  /**
   * Формирование системного контекста для инжекта модели
   */
  getStatePromptInjection(sessionId = 'default') {
    const sid = sessionId || 'default';
    const goal = this.goals.get(sid);
    if (!goal || goal.state !== GoalState.RUNNING) {
      return '';
    }

    const snapshot = this.getSnapshot(sid);
    const lang = goal.lang || detectLanguage(snapshot.title);
    const hasMilestones = snapshot.milestones.length > 0;
    const etaText = snapshot.formattedETA ? ` (ETA: ${snapshot.formattedETA})` : '';

    let nudgeText = '';
    if (goal.pendingNudge) {
      const userFeedback = goal.pendingNudge;
      goal.pendingNudge = null;
      nudgeText = lang === 'ru'
        ? `\n\n🚨 СРОЧНОЕ УТОЧНЕНИЕ / НАПРАВЛЕНИЕ ОТ ПОЛЬЗОВАТЕЛЯ:\n"${userFeedback}"\nОбязательно скорректируй свои ближайшие действия с учётом этого замечания!\n`
        : `\n\n🚨 URGENT USER CLARIFICATION / STEERING:\n"${userFeedback}"\nYou must adjust your immediate actions according to this guidance!\n`;
    }

    if (lang === 'ru') {
      const milestonesText = hasMilestones
        ? snapshot.milestones.map((m, i) => `  ${i + 1}. [${m.status.toUpperCase()}] ${m.title}${m.notes ? ` (${m.notes})` : ''}`).join('\n')
        : '  (План работ ещё не сформирован — немедленно вызови goal_set_milestones со списком шагов!)';

      return nudgeText + `\n\n[DSH GOAL MODE ACTIVE]
Цель: "${snapshot.title}"
Время работы: ${snapshot.formattedElapsed}${etaText} | Итерация: ${snapshot.iterationsCount}/${snapshot.maxIterations}
План работ:
${milestonesText}

Инструкции Goal Mode (СТРОГО ОБЯЗАТЕЛЬНЫ К ВЫПОЛНЕНИЮ):
1. ${hasMilestones ? 'Выполняй текущий активный пункт плана работ.' : 'ТВОЙ ПЕРВЫЙ ШАГ: Немедленно вызови инструмент goal_set_milestones со списком пунктов плана работ (3-7 конкретных шагов). Запрещено выполнять работу или завершать turn без вызова goal_set_milestones!'}
2. По мере выполнения каждого шага обязательно отмечай его статус через инструмент goal_update_progress (status: "in_progress" перед началом шага, status: "completed" по его завершении с кратким notes).
3. Когда все пункты плана будут выполнены, вызови инструмент goal_finish с подробным итоговым резюме достигнутых результатов.`;
    }

    const milestonesText = hasMilestones
      ? snapshot.milestones.map((m, i) => `  ${i + 1}. [${m.status.toUpperCase()}] ${m.title}${m.notes ? ` (${m.notes})` : ''}`).join('\n')
      : '  (Work plan is not yet established — call goal_set_milestones immediately with initial steps!)';

    return nudgeText + `\n\n[DSH GOAL MODE ACTIVE]
Goal: "${snapshot.title}"
Elapsed Time: ${snapshot.formattedElapsed}${etaText} | Iteration: ${snapshot.iterationsCount}/${snapshot.maxIterations}
Work Plan:
${milestonesText}

Goal Mode Instructions (MANDATORY TO FOLLOW):
1. ${hasMilestones ? 'Execute the current active milestone from the work plan.' : 'YOUR FIRST STEP: Immediately call tool goal_set_milestones with the list of milestones (3-7 concrete steps). You must not execute work or finish turn without calling goal_set_milestones!'}
2. As each milestone progresses, update its status via tool goal_update_progress (status: "in_progress" before starting, status: "completed" upon completion with brief notes).
3. When all milestones are completed, call tool goal_finish with a detailed summary of achieved results.`;
  }
}
